version: "3.4"

services:
  db:
    image: mariadb:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: ./docker/volumes/db-local
        target: /var/lib/mysql
        bind:
          propagation: "shared"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/root_password
      MYSQL_USER: /run/secrets/db_user
      MYSQL_PASSWORD: /run/secrets/db_password
      MYSQL_DATABASE: wordpress
    secrets:
      - root_password
      - db_user
      - db_password
    networks:
      - dbnet
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: ./docker/volumes/wp-local
        target: /var/www/html
        bind:
          propagation: "shared"
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    networks:
      - dbnet
      - wpnet

secrets:
  root_password:
    file: ./docker/secrets/root_password.txt
  db_user:
    file: ./docker/secrets/db_user.txt
  db_password:
    file: ./docker/secrets/db_password.txt

networks:
  dbnet:
  wpnet:
